site_name: 解籤王 Fortune Boss
site_url: https://fortuneboss.technologymochia.org
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: orange
    accent: yellow
    toggle:
      icon: material/brightness-4
      name: Switch to system preference  
  - media: "(prefers-color-scheme)"
    primary: orange
    accent: yellow
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 
    primary: orange
    accent: yellow
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  features:
      - navigation.tabs
      - navigation.tabs.sticky

nav:
    - 首頁: index.md
    - 服務項目:
      - 服務說明: service.md
      - 觀音籤: guanyin.md
      - 月老籤: thunderrain.md
      - 甲子籤: jiazi.md
    - 捐款方式: price.md
    - 關於我們: about.md

markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
  
extra:
  generator: false
  social:
    - icon: material/email
      link: "mailto:chwc@technologymochia.org"
    - icon: material/web
      link: "https://portaly.cc/kaitshiam"
    - icon: simple/line
      link: "https://line.me/R/ti/p/@223qrbck"
copyright: Copyright © 2023 Fortune Boss
